products/mock-ee.conf

JIRA Issue: https://vasdvp.atlassian.net/browse/CCE-54
DU PR: https://github.com/department-of-veterans-affairs/health-apis-mock-eligibility-and-enrollment-deployment/pull/2

Incremented mock-ee DU for artifact spelling issue..

---

products/community-care.conf
products/mock-ee.conf

JIRA Issues:
- https://vasdvp.atlassian.net/browse/CCE-77
- https://vasdvp.atlassian.net/browse/CCE-79
Both CCE & Mock-EE have been updated to utilize the new DU property level encryption.

Updated CCE & Mock-EE to utilize DU property level encryption

---

products/urgent-care.conf

Had a QE change without the needed UC change.

Update DU config

---

products/carma.conf
products/community-care.conf
products/data-query.conf
products/urgent-care.conf

Deploying CCE from *staging_lab* to *staging*.
MR: https://github.com/department-of-veterans-affairs/vertx-apis/pull/291/files

Community Care Eligibility 1.0.41 to LAB

---

products/carma.conf
products/community-care.conf
products/data-query.conf
products/urgent-care.conf

MR: https://github.com/department-of-veterans-affairs/vertx-apis/pull/293

CCE in production

---

products/data-query.conf

Actually enable kong logging...

MR-1900182

---

products/urgent-care.yaml

Urgent Care CPU/Memory Limits

---

products/hotline.yaml

VIEWS Hotline Resource Quota

---

products/squares.yaml

VIEWS Squares ResourceQuota

---

products/gal-processor.conf
products/gal-processor.yaml

Minor gal-processor app changes. The promotatron hasn't been set up for it yet

Narrow ingress and update DU

---

products/community-care.yaml

CPU: 0.15 Cores
Memory: 5.5 GB

CCE CPU/Memory Limits

---

products/data-query.conf

[MR-1900209](https://github.com/department-of-veterans-affairs/vertx-apis/pull/368)

MR-1900209

---

products/community-care.conf
products/community-care.yaml

https://vasdvp.atlassian.net/browse/CCE-138

Add second ingress route for CCE to bypass OAuth

---

Jenkinsfile
environments/qa.conf
products/carma-fms-connector.conf
products/carma-fms-connector.yaml
products/community-care.conf
products/community-care.yaml
products/data-query.conf
products/hotline.conf
products/urgent-care.conf

https://github.com/department-of-veterans-affairs/vertx-apis/pull/395/files

MR 1900228

---

bin/attach-deployment-unit-to-lb
bin/detach-deployment-unit-from-lb
bin/remove-all-green-routes
products/carma.conf
products/community-care.conf
products/data-query.conf

Deploying CARMA to Lab.
MR: 1900255
PR: https://github.com/department-of-veterans-affairs/vertx-apis/pull/427

Staging lab to Lab

---

toolkit-base/build-toolkit-base.sh

```
load-balancer
attach-deployment-unit-to-lb
detach-deployment-unit-to-lb
remove-all-green-routes
```

Additional tools for the toolkit base

---

toolkit-base/build-toolkit-base.sh

I need more of these tools to help with smoke testing from `health-apis-colonel-cluster`

Added more tools to support running product tests

---

products/exemplar.yaml

https://vasdvp.atlassian.net/browse/DEVOPS-350

Added exemplar resource quota

---

products/gal-processor.yaml

https://vasdvp.atlassian.net/browse/DEVOPS-264

Added gal processor resource quota

---

products/data-query.conf
products/data-query.yaml

https://github.com/department-of-veterans-affairs/vertx-apis/pull/501

MR 1900318

---

products/bulk-fhir.conf
products/data-query.conf
products/data-query.yaml

https://github.com/department-of-veterans-affairs/vertx-apis/pull/505

MR 1900320

---

products/bulk-fhir.conf
products/data-query.conf
products/data-query.yaml

Reverts department-of-veterans-affairs/health-apis-deployer#232

Revert "MR 1900320"

---

products/bulk-fhir.conf
products/data-query.conf
products/data-query.yaml

Reverts department-of-veterans-affairs/health-apis-deployer#233

MR 1900320 - The Second Revert

---

products/data-query.conf
products/data-query.yaml
products/monitoring.conf
products/monitoring.yaml
products/squares.conf

https://github.com/department-of-veterans-affairs/vertx-apis/pull/508/files

MR 1900323

---

products/dmc-vet-search.conf
products/dmc-vet-search.yaml

This PR affects the DMC VetSearch API deployment.
The resource quota sections have been removed for now until we can decide on values that make sense based on user traffic.
Currently this API is not in production and we have no user metrics.

DMC VetSearch - remove resource quota and update DU version

---

Jenkinsfile
products/bulk-fhir.conf
products/community-care.conf
products/data-query.conf
products/email-to-case.conf
products/email-to-case.yaml
products/mock-ee.conf

DO NOT MERGE YET until CCE 1.0.77 is in Staging-Lab!!
https://vasdvp.atlassian.net/browse/SSS-62
Adding new test patients for VAOS.
MR: https://github.com/department-of-veterans-affairs/vertx-apis/pull/515

MockEE 1.0.36 to LAB and CCE 1.0.77 to LAB

---

products/exemplar.yaml

Increased exemplar resource quota to support hpa

---

Jenkinsfile

Product files already exist, only thing I'm not sure about is lack of resource quotas

Adding qms and watrs to dropdown

---

Jenkinsfile
products/fall-risk.conf
products/fall-risk.yaml

Story: https://vasdvp.atlassian.net/browse/SHANK-233

add fall risk product

---

Jenkinsfile

Forgot to add ssn-sensitivity to the dropdown with its new DU. Please let me know if there's anything else that needs to be updated to connect everything together, this has changed since I last saw it.

Add SSN-Sensitivity to Deployer Dropdown

---

products/dmc-vet-search.conf

This PR supports the deployer product `dmc-vet-search` to get into Staging.
The new DMC VetSearch deployment unit version is now 1.0.19.

DMC VetSearch to Staging

---

products/dmc-vet-search.conf

Upgrade dmc-vet-search to DU 1.0.20

---

products/provider-directory.conf

https://github.com/department-of-veterans-affairs/vertx-apis/pull/581

MR-1900382

---

products/hotline.yaml

https://vasdvp.atlassian.net/browse/PIV-198

Less greedy ingress

---

build.sh

@jgarnhart-va should fix your issue, woops :(

Fix Unbound Variable : Deployment Mode

---

Jenkinsfile
ingress.tests
products/sfdc-mvi-ent.conf
products/sfdc-mvi-ent.yaml

This PR adds the SFDC MVI Enterprise app to DVP.

Add product sfdc-mvi-ent

---

ingress.tests

This branch was run in Jenkins and deployed to QA as expected.
https://tools.health.dev-developer.va.gov/jenkins/job/department-of-veterans-affairs/job/health-apis-deployer/job/task%252FVECMS-ingress-test-to-dmc-vetsearch/3/console

Added routes for DMC VetSearch

---

Jenkinsfile
products/data-query.conf

https://github.com/department-of-veterans-affairs/lighthouse-maintenance/pull/5

mr 2000005: data-query to lab

---

products/community-care.conf

https://vasdvp.atlassian.net/browse/SHANK-294

SHANK-294 Deploy CCE to A and B

---

products/bulk-fhir.conf
products/fall-risk.conf

https://github.com/department-of-veterans-affairs/lighthouse-maintenance/pull/10

Staging lab

---

products/carma.conf
products/ssn-sensitivity-vimt.conf
products/unifier-kong.conf

Reverts department-of-veterans-affairs/health-apis-deployer#337

Revert "MR-2000017"

---

Jenkinsfile
bin/deployment-status
build.sh

https://vasdvp.atlassian.net/browse/SHANK-328
https://tools.health.dev-developer.va.gov/jenkins/job/department-of-veterans-affairs/job/health-apis-deployer/job/SHANK-328-status-artifact-when-custom-cluster/5/artifact/status.us-gov-west-1a.json

Shank 328 status artifact when custom cluster

---

products/urgent-care.conf

https://vasdvp.atlassian.net/browse/SHANK-342

SHANK-342 UC automatic zones

---

toolkit-base/bin/whats-deployed

https://vasdvp.atlassian.net/browse/SHANK-355

SHANK-355 Add credentials to whats-deployed

---

Jenkinsfile
ingress.tests
products/facilities-cdw.conf
products/facilities-cdw.yaml

https://vasdvp.atlassian.net/browse/IN-96

IN-96 Add facilities-cdw app

---

products/facilities-cdw.conf

https://vasdvp.atlassian.net/browse/SHANK-379

SHANK-379 Lighthouse prefix

---

toolkit/dtk

Windows users need to have their directories in a proper format. This fixes that.

Detect operating system and set variable if windows is detected

---

Jenkinsfile
ingress.tests
products/facilities-cdw.conf
products/facilities.conf
products/facilities.yaml

https://vasdvp.atlassian.net/browse/SHANK-391

rename to facilities-collector

---

ingress.tests
products/facilities.conf
products/facilities.yaml

https://vasdvp.atlassian.net/browse/SHANK-514
I tested this using the `/all` endpoint on the blue qa load-balancer. Both with and without `/services`.

Shank 514 refactor ingress

---

bin/load-balancer
build.sh

https://vasdvp.atlassian.net/browse/SHANK-555

Shank 555 detect duplicate rules

---

bin/load-balancer

https://vajira.max.gov/browse/API-917
Example Jenkins Deployment:
https://tools.health.dev-developer.va.gov/jenkins/view/Shanktopus/job/department-of-veterans-affairs/job/health-apis-deployer/job/API-917-deployment-noisiness/8/console

Api 917 deployment noisiness

---

products/carma-vssc.conf

Changes:
- Using a better health_check_path

Using /actuator/health for health checks.

---

bin/load-balancer
bin/wait-for-lb
build.sh

[API-1306](https://vajira.max.gov/browse/API-1306)

Api 1306 reduce aws calls

---

Jenkinsfile
ingress.tests
products/carma-mpi-bulk.conf
products/carma-mpi-bulk.yaml

Resolved deployment issues from the [previous PR](https://github.com/department-of-veterans-affairs/health-apis-deployer/pull/390).
Successfully deployed to qa from this branch. Rate-limiting pending DevOps's review.

Carm 11851 setup mpi bulk

---

products/sf-d-to-c-handler.conf

No
Yes
https://tools.health.dev-developer.va.gov/jenkins/job/department-of-veterans-affairs/job/health-apis-deployer/job/dmc-debt-to-contact-add-az-c/3/console
Nope
Nope
No. I'm just adding my app to AZ C in addition to A and B.

DU_AUTOMATIC_AVAILABILITY_ZONES=abc

---

products/facilities.yaml

Are load balancer rules being removed or renamed? no
https://vajira.max.gov/browse/API-1691
branch deployment: https://tools.health.dev-developer.va.gov/jenkins/job/department-of-veterans-affairs/job/health-apis-deployer/job/API-1691-kongectomy/3/
deployment unit PR: https://github.com/department-of-veterans-affairs/lighthouse-facilities-deployment/pull/46

API-1691 remove facilities kong

---

README.md

Is this a new product? n/a
Has this been deployed successfully from a branch? n/a
Are load balancer rules being removed or renamed? n/a
Are Kubernetes namespaces being removed or renamed? n/a

Application Removal Documentation

---

products/carma-cdw.conf

updating cdw deployment AZs

---

products/carma-bgs.conf

updating az

---

products/carma-vssc.conf

updating VSSC AZ

---

ingress.tests

Updating ingress tests for Carma apps

---

products/data-query.yaml

Added Kubernetes Ingress path for ETL status monitoring

---

products/data-query.yaml

Has this been deployed successfully from a branch? N/A
Are load balancer rules being removed or renamed? no
Are ingress definitions being removed or renamed? yes
Has DevOps been consulted on resource limits? N/A

API-1562 additional paths for etl-status

---

Jenkinsfile
ingress.tests
products/vistalink.conf
products/vistalink.yaml

Is this a new product? -- yes
Has this been deployed successfully from a branch? -- yes
Are load balancer rules being removed or renamed? -- no
Are ingress definitions being removed or renamed? -- no
Are Kubernetes namespaces being removed or renamed? -- no 
Has DevOps been consulted on resource limits? -- not yet, :skull: application

Api 2725 vl deployer

---

Jenkinsfile
ingress.tests
products/patient-generated-data.conf
products/patient-generated-data.yaml

Is this a new product? yes
Are load balancer rules being removed or renamed? yes
Are ingress definitions being removed or renamed? yes
Are Kubernetes namespaces being removed or renamed? yes
Has DevOps been consulted on resource limits? yes

API-3033 Add PGD

---

Jenkinsfile
products/mock-emis.conf
products/mock-emis.yaml

Yes.
Yes.
No.
No.
No.
Same resource limits as other mocked services are being applied.

add mock-emis configurations

---

Jenkinsfile
ingress.tests
products/insurance.conf
products/insurance.yaml

deploy insurance skeleton

---

ingress.tests
products/data-query.yaml
products/scheduling.yaml

no
yes
https://tools.health.dev-developer.va.gov/jenkins/job/department-of-veterans-affairs/job/health-apis-deployer/job/API-3225-external-scheduling-ingress/3/console
https://tools.health.dev-developer.va.gov/jenkins/job/department-of-veterans-affairs/job/health-apis-deployer/job/API-3225-external-scheduling-ingress/4/console
no
yes
no
no

move appointment to scheduling

---

products/scheduling.conf
products/scheduling.yaml

no
yes
https://tools.health.dev-developer.va.gov/jenkins/job/department-of-veterans-affairs/job/health-apis-deployer/job/API-3225-scheduling-lb-rule/8/console
no
no
no
no

Api 3225 scheduling lb rule

---

products/insurance.conf
products/insurance.yaml

Added fhir path to Insurance

---

ingress.tests
products/patient-generated-data.yaml

Are load balancer rules being removed or renamed? no
Are ingress definitions being removed or renamed? yes

API-3881 strip services from PGD path

---

products/vista-fhir-query.conf

API-4535-deployment-machinery

---

products/docserver.conf

Yes
No, needs D2.
No.
No.
No.
No. This is an ECS deployment.

add docserver.conf; D2 -> ECS

---

products/docserver.conf

add missing du key

---

products/clinical-health-api.conf
products/vista-fhir-query.conf

create clinical-health-api conf and move rule out of vista-fhir-query
