department-of-veterans-affairs/health-apis-deployer

build.sh
products/mock-ee.conf
products/mock-ee.yaml

JIRA Issue: https://vasdvp.atlassian.net/browse/CCE-61
as well as https://vasdvp.atlassian.net/browse/CCE-62
Lab config and test vars added to the deployment unit for Mock-EE.  Deploying to QA first, will have an MR and PR for the actual lab deployment later.
Also, the application has been updated to handle the version part of the path per CCE-62.  The LB & Ingress have been updated to no longer include version information.

Added Lab configs as part of DU, moved version routing to app responsibility

---

products/gal.yaml

CPU: 1 Core
Memory: 6 GB
Note: Temporarily deploy GAL with a ResourceQuota successfully to QA, test and verify, then finally remove GAL from QA.

Enforce cpu/mem limits for GAL

---

products/gal.yaml

Use correct unit for denoting gigabyte: `G` vs `Gi`

Fix GAL Memory Quota

---

products/community-care.yaml

This increase is based on the observed usage required for successfully starting up applications in CCE.
**Before**: 0.15 Cores
**After**: 6 Cores 
(1 Core for Community Care + 1 Core for Kong) x 3 replicas

Increased CCE CPU Limit 

---

products/community-care.yaml

Increasing CCE memory quota based on observed restarts of Kong from hitting its memory limit.
**Before**
Memory: 5.5 GB
**After**
Memory: 9 GB
Breakdown: (community-care pod 2GB x 3 replicas) + (kong pod 1GB x 3 replicas) = 9 GB

Increase CCE memory quota

---

bin/attach-deployment-unit-to-lb
bin/detach-deployment-unit-from-lb
bin/remove-all-green-routes

The deployer should now better detect and fail when AWS calls are unavailable.

Deployer detects AWS failures

---

Dockerfile
Jenkinsfile
deployment-unit.md
environments/lab.conf
environments/production.conf
environments/qa.conf
environments/staging-lab.conf
environments/staging.conf
environments/uat.conf
products/data-query.conf
products/gal-processor.conf
products/urgent-care.conf

Jenkles is now using the EC2 role 'project-devtools-role'. The AWS credentials have been commented out for all users on the instance and removed from the Jenkinsfile for the QA Deployer. Testing deployments.

Removing AWS Credentials to test EC2 role

---

products/hotline.conf
products/squares.conf

The issue with the old health check is it was JUST the experience.  So when AZ B went down last night the experience calls were still working?  Because the workers would respond on the first call.  But they couldn't talk between themselves.
These new health checks will test communication within the cluster which is closer to the correct answer...

updated Target Group Health Checks for Hotline and Squares

---

products/urgent-care.yaml

Using NetworkPolicies in the urgent-care.yaml, enforce namespace isolation such that pods in the uc namespace may only receive traffic from other pods within the same namespace or pods within the ingress namespace.
related story: https://vasdvp.atlassian.net/browse/PIV-23

Add ingress and uc namespace NetworkPolicies to urgent-care yaml

---

products/dmc-vet-search.conf
products/dmc-vet-search.yaml

This PR adds the product `dmc-vet-search` to the deployer.
The `dmc-vet-search` app is very much like `carma-search` in that it is able to search MVI  and other VA endpoints for veteran demographic and identity information.

adding product dmc-vet-search

---

Jenkinsfile
products/email-to-case.conf
products/email-to-case.yaml

This PR adds support for `email-to-case` in the deployer.
The application, email-to-case, falls under VIEWS development to monitor and process a list of configured mailboxes, creating corresponding Salesforce Case records.  Also included are several REST endpoints for monitoring that processing and the current configuration.
For resource utilization limits, I originally utilized carma-fms as a template, but was able to reduce the limits after Monica monitored in Grafana.  I also previously confirmed the `/email-to-case/v0` with the Devops team.

Added email-to-case configuration.

---

products/hotline.yaml

Should be merged **before** https://github.com/department-of-veterans-affairs/health-apis-hotline-deployment/pull/5

Increased hotline resource quota to support hpa

---

products/urgent-care.yaml

Should be merged before https://github.com/department-of-veterans-affairs/health-apis-urgent-care-deployment/pull/33

Increase UrgentCare resource quota to support hpa

---

products/squares.yaml

Should be merged before https://github.com/department-of-veterans-affairs/health-apis-squares-deployment/pull/5

Increased Squares resource quota to support hpa

---

products/community-care.yaml

Should be merged before https://github.com/department-of-veterans-affairs/health-apis-community-care-deployment/pull/30

Increased Community Care resource quota to support hpa

---

products/provider-directory.yaml

Should be merged before https://github.com/department-of-veterans-affairs/health-apis-provider-directory-deployment/pull/10

Increased provider-directory resource quota for hpa

---

products/carma.yaml

Should be merged before https://github.com/department-of-veterans-affairs/health-apis-carma-search-deployment/pull/12

Increased carma search resource quota for hpa

---

products/urgent-care.yaml

Well-Known requests for R4 currently have nowhere to go. They were removed from UC's ingress rules and there's no unifier set up yet to receive them.
https://api.va.gov/services/fhir/v0/r4/.well-known/smart-configuration

UC should still be taking well-known requests

---

products/hotline.conf
products/ssn-sensitivity-vimt.conf
products/ssn-sensitivity-vimt.yaml

Splitting up hotline and ssn-sensitivity since they’re separate functionality and it should cut down on danger zone deployments.  Please see PIV-79 (and related stories) for additional context.

Split SSNSensitivity-VIMT from Hotline.

---

Jenkinsfile
products/unifier-kong.conf
products/unifier-kong.yaml

This also has an LB rule in the hopes we can deploy this up to PROD without danger zone builds the whole way. If that plan sounds good I need to get an accompanying PR approved real quick to prepend to the paths that we test with our test image.
Either way, after testing unifier in various environments we'd make a second deployer PR that:
* takes the unifier-test portion of the ingress rule out 
* adds the LB rules for UK
* edits the ingress rules for DQ and UC that handle metadata and well-known
We'd then need to redeploy UK to all environments as well as DQ and UC. The unifier-test LB rule should be taken away if it ends up being used.

Ingress rule for testing

---

products/unifier-kong.conf

Fixing issue where files were incorrectly named prod.conf and prod.testvars instead of production.conf and production.testvars for Unifier Kong DU

Update DU version with prod -> production rename

---

products/carma-fms-connector.conf

carma-fms-connector can currently only deploy to one AZ, adding the configuration for the deployer so we can have automatic deployments.

Add Specific AZ to carma-fms-connector

---

products/email-to-case.conf
products/gal-processor.conf
products/gal.conf
products/qms.conf
products/squares.conf
products/watrs.conf

Added `DU_AUTOMATIC_AVAILABILITY_ZONES` setting per PIV-228.
https://vasdvp.atlassian.net/browse/PIV-228
Deployer `{product}.conf` updated for any Pivot! owned integrations including:
- GAL (Only one AZ, A)
- GAL-PROCESSOR (Same as above)
- SQUARES (AZs A and B only)
- QMS (Only one AZ, A)
- WATRS (Only one AZ, A)

Added DU_AUTOMATIC_AZ settings for Pivot! applications.

---

products/sfdc-mvi-ent.conf

Liveliness and readiness probes are now to use `/actuator/health` rather than `/actuator/info`

SFDC-MVI-ENT DU Probe changes

---

.gitignore
bin/ryan-secrets
toolkit/build-toolkit.sh

Fixes issue during deployment:
```
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
```
Determined to be caused by the update of the `openssl` command in centos8

Api 2196 ryan secrets openssl

---

ingress.tests
products/patient-generated-data.yaml

Are load balancer rules being removed or renamed? no
Are ingress definitions being removed or renamed? yes
revert https://github.com/department-of-veterans-affairs/health-apis-deployer/pull/442

Revert "API-3881 strip services from PGD path"

---

products/smart-cards.conf

Dedicated load-balancer rules for smart cards.
`https://blue.qa.lighthouse.va.gov/fhir/v0/r4/Patient/123/$HealthWallet.issueVc` is accessible
`https://green.qa.lighthouse.va.gov/fhir/v0/r4/Patient/123/$HealthWallet.issueVc` is not
Are load balancer rules being removed or renamed? yes
Are ingress definitions being removed or renamed? no

API-5280 smart cards external load balancer rules
